apiVersion: v1
kind: Service
metadata:
  name: mqtt 
spec:
  type: ClusterIP 
  selector: 
    app: mqtt
  ports:
  - name: mosquitto-web
    protocol: TCP
    port: 9001
    targetPort: 9001
  - name: mosquitto
    protocol: TCP
    port: 1883
    targetPort: 1883
