apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mqtt 
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: mqtt
    spec: 
      containers:
      - name: mqtt
        image: eclipse-mosquitto:latest
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
        - mountPath: /mnt/azure/mqtt_home/mosquitto/config/mosquitto.conf
          name: mqtt-home
      volumes:
      - name: mqtt-home 
        persistentVolumeClaim: 
          claimName: azure-managed-disk-mqtt
