apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-mqtt
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 15Mi
